---
all:
  children:
    shelf:
      vars:
        ansible_user: "{{ lookup('env','USER') }}"
        provision_domain: national.core.bbc.co.uk
      hosts:
        3gbbmfsiep6001:
        3gbbmfsiep6002:
    cache:
      hosts:
        3gbbmfsiep6011:
        3gbbmfsiep6012:
    test:
      hosts:
        3gbbmfsiep6001:
    signiant:
      hosts:
        3gbbmapfbd6001:
    shelfdr:
      hosts:
        3gbbmfsiep6005:
    allnodes:
      hosts:
        3gbbmfsiep6001:
        3gbbmfsiep6002:
        3gbbmfsiep6011:
        3gbbmfsiep6012:
        3gbbmfsiep6005:
        3gbbmfsfbd6001:
