---
- name: AD Integration for Ubuntu
  hosts: test
  gather_facts: yes
  serial: 2
  vars:
    ansible_host: "{{ provision_ipaddress }}"
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  tasks:
  - name: Hold bbcnpf-defaultserver package
    become: yes
    become_method: sudo
    dpkg_selections:
      name: bbcnpf-defaultserver
      selection: hold

  - name: Remove bbcnpf-joindomain
    become: yes
    become_method: sudo
    apt:
      name: bbcnpf-joindomain
      state: absent
    ignore_errors: true

#  - name: Join system to AD for Samba
#    become: yes
#    become_method: sudo
#    command: /bin/bash -c "net ads join -k"
#    when: ads_bound is failed

  - name: Restart Samba processes
    become: yes
    become_method: sudo
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - smbd
      - nmbd

  - name: Change bscadmin account password for this server
    become: yes
    become_method: sudo
    user:
      name: bscadmin
      password: "{{ bscadmin_password }}"

  - name: Change issue file
    become: yes
    become_method: sudo
    lineinfile:
      path: /etc/issue
      regexp: '^Login available from NATIONAL'
      line: 'BSC AD Integrated Login from NATIONAL'

  - name: Change issue.net file
    become: yes
    become_method: sudo
    lineinfile:
      path: /etc/issue.net
      regexp: '^Login available from NATIONAL'
      line: 'BSC AD Integrted Login from NATIONAL'

  - name: Check if old AD accounts exist locally
    become: yes
    become_method: sudo
    command: /bin/bash -c 'grep "x:2000" /etc/passwd'
    register: ad_local
    changed_when: false
    ignore_errors: true

  - name: Remove accounts and directories generated by bbcnpf-joindomain
    become: yes
    become_method: sudo
    shell: nohup /bin/bash -c 'pkill -u ere-mid-tf ; while IFS=":" read -r user x uid x; do [[ $uid -gt 1999 && $uid -lt 2500 ]] && userdel -r "$user"; done </etc/passwd ; groupdel domainusers'
    ignore_errors: true
    when: ad_local is succeeded
