---
all:
  children:
    clustercontrol:
      vars:
        ansible_user: "{{ lookup('env','USER') }}"
        provision_domain: national.core.bbc.co.uk
      hosts:
        3gbbmapbds1001:
        3gbbmapbds1002:
    ccactive:
      hosts:
        3gbbmapbds1001:
    ccstandby:
      hosts:
        3gbbmapbds1002:
    proxysql:
      hosts:
        3gbbmapbds1011:
        3gbbmapbds1012:
    galera:
      hosts:
        3gbbmdbbds1001:
        3gbbmdbbds1002:
        3gbbmdbbds1003:
    allnodes:
      hosts:
        3gbbmapbds1001:
        3gbbmapbds1002:
        3gbbmapbds1011:
        3gbbmapbds1012:
        3gbbmdbbds1001:
        3gbbmdbbds1002:
        3gbbmdbbds1003:

